### ISSUE TITLE
[4.2.3] Items sometimes flicker the use prompt on and off making it hard to pick them up

### ISSUE THREAD

**Issue by StroggVorbis** [argv-minus-one/gzdoom-use-to-pickup#7]
Description is in the title.

**Comment by argv-minus-one** [comment]
I'm sorry, but I haven't been playing for quite some time now. If anyone else could fix this, I'd appreciate a PR.

Side note: your user name is awesome.

**Comment by argv-minus-one** [comment]
As we discussed on Discord, this was apparently a GZDoom bug that's been fixed, so I'm closing this. Thanks again for letting me know!
